# Site settings
author: Blend Ibraj
title: Blend's Blog
header-img: img/home-bg.png
email: blendi.ibraj96@gmail.com
copyright_name: Blend Ibraj
description: > # this means to ignore newlines until "baseurl:"
  A beginner's path to programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Bibraj96

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
